In [1]:
import numpy as np
import pandas as pd

In [2]:
from features_xtrct import PhraseExtract, PhraseExtract1

In [3]:
df = pd.read_csv('PhraseTest_Data.csv')

In [4]:
df

,Name,Age,Grade Level,Gender,School,Question 1,Question 2
0,Jazz Trickxia,11,6,F,LDES,I want to be a photographer because i want to ...,The most valuable i learned is always fight Ne...
1,Xian Gabriel O. Romero,12,6,M,LDES,when i grow up i Want to be a FireFighter. bec...,the most valuable lesson i've learned is never...
2,Jhermaine Dale M. Ramos,11,6,F,LDES,I want to be a Artist when i grow up . If i co...,"I learned About some things in Drawing , Sketc..."
3,Jade Allison Panganiban,11,6,F,LDES,i want to be Medschool because i want to help ...,The Most i learn valuable is never give up and...
4,BEATRIZE ANN P. SARMIENTO,11,6,F,LDES,I WANT TO BE A DOCTOR WHEN I GROW UP AND IF I ...,I LEARNED IN MY LIFE IS ABOUT TO RESPECT THE P...
5,Rhianne Alexa C. Tabora,11,6,F,LDES,I want to be a flight attendant when i grew up...,The most valuable i learned in my life is no m...
6,Eunice A. Lagazon,12,6,F,LDES,"I want to be a doctor , i will be a good stude...",The most value of my life is to be kind and be...
7,Cassandra Nicole L. Mendoza,12,6,F,LDES,i want to be a teacher. i will finish my schoo...,The most valuable lesson i learned is no matte...
8,Faith Margaret Oranza,11,6,F,LDES,I want to be a nurse so one day i will help ma...,"Be kind , respectful to people and never put y..."
9,Munique Cometa,12,6,F,LDES,I WANT TO BE NURSE SO I CAN HELP THE DOCTOR TO...,WELL I THINK THATS A GOOD QUESTION HMM... DON...
10,Juliana Brent Gabion,11,6,F,LDES,When i grow up i want to be a nurse beacause h...,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         11 non-null     object
 1   Age          11 non-null     int64
 2   Grade Level  11 non-null     int64
 3   Gender       11 non-null     object
 4   School       11 non-null     object
 5   Question 1   11 non-null     object
 6   Question 2   10 non-null     object
dtypes: int64(2), object(5)
memory usage: 744.0+ bytes

In [6]:
features_list = list()

for index, row in df.iterrows():
    print(f"row:{index}")
    Phrase = PhraseExtract1(question='What do you want to be when you grow up? How will you get there?', text=row['Question 1'])
    print(Phrase.FeatureList())
    features_list.append(Phrase.FeatureList())

row:0
[116, 0.7077499999999999, 3.8879310344827585, 19, 5, 5, 25, 19, 6, 77.37, 98.0, 1, 4, 1, 0.7742932464128051]
row:1
[30, 0.8125, 3.8, 3, 0, 2, 5, 6, 0, 86.71, 47.666666666666664, 2, 0, 1, 0.6781352769759128]
row:2
[25, 0.8461538461538461, 3.24, 2, 0, 1, 6, 6, 0, 101.09, 53.0, 1, 1, 0, 0.8194410529676285]
row:3
[38, 0.6578947368421053, 3.6578947368421053, 2, 2, 1, 11, 8, 6, 66.75, 87.5, 0, 2, 0, 0.8451535831518575]
row:4
[33, 0.7142857142857143, 3.1515151515151514, 5, 0, 1, 6, 7, 1, 71.82, 68.5, 1, 1, 0, 0.3266902954254142]
row:5
[25, 0.7777777777777778, 3.28, 3, 1, 1, 5, 6, 1, 101.09, 53.5, 1, 1, 0, 0.8568455167364906]
row:6
[16, 0.8333333333333334, 2.875, 2, 2, 0, 3, 2, 1, 97.54, 64.0, 0, 1, 0, 0.8059070285711758]
row:7
[17, 0.7894736842105263, 3.176470588235294, 3, 0, 0, 4, 3, 0, 105.15, 35.5, 2, 0, 0, 0.7822950323806248]
row:8
[14, 0.9333333333333333, 3.0, 3, 1, 0, 2, 2, 0, 99.57, 56.0, 1, 0, 0, 0.8387830548036798]
row:9
[41, 0.6904761904761905, 3.682926829268293, 7, 0, 3, 6, 7, 2, 72.16, 63.666666666666664, 1, 2, 0, 0.15337375887117005]
row:10
[39, 0.6923076923076923, 3.58974358974359, 6, 2, 1, 8, 8, 2, 65.73, 178.0, 0, 1, 0, 0.8407465350399727]